[package]
name = "gateway"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
arrayref = "0.3.7"
num-derive = "0.4.1"
num-traits = "0.2.17"
solana-program = "1.17.6"
thiserror = "1"

[dev-dependencies]
solana-program-test = "1.17.6"
solana-sdk = "1.17.6"
