[package]
name = "gateway"
version = "0.1.0"
edition = "2021"


[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.17.6"

[dev-dependencies]
solana-program-test = "1.17.6"
solana-sdk = "1.17.6"
